# Generated by Django 5.1.1 on 2024-09-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='group_id',
            field=models.IntegerField(null=True),
        ),
    ]
