# Generated by Django 5.1.1 on 2024-09-10 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_alter_country_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='country_code',
            new_name='countryCode',
        ),
    ]
