# Generated by Django 5.1.1 on 2024-09-10 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_rename_country_code_country_countrycode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='group_id',
            new_name='groupId',
        ),
    ]
